FROM ubuntu:18.04
RUN apt-get update && apt-get install --yes python3-poppler-qt5
RUN apt-get update && apt-get install --yes python3-pip
RUN python3 -m pip install pdftitle
RUN python3 -m pip install loguru
RUN python3 -m pip install arxiv
